### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by XiXiaPdx**
I'm pretty green with github actions so I forgot I needed to checkout my code. 

I copy pasta'ed the example and received a build error. Took me a while to figure this out. I got lucky looking at the v1 branch and realized what I was missing.

Maybe this will help someone else new avoid my experience!

### CODE REVIEW

**Comment by crazy-max** [comment]
@XiXiaPdx Checkout action is not required when [Git context is used (default one)](https://github.com/docker/build-push-action/blob/b1b7db3498a1941bc89504b474567da7ddc1341c/src/context.ts#L10)

**Comment by XiXiaPdx** [comment]
> @XiXiaPdx Checkout action is not required when [Git context is used (default one)](https://github.com/docker/build-push-action/blob/b1b7db3498a1941bc89504b474567da7ddc1341c/src/context.ts#L10)

Ok.  This is the error in my build from the action run logs if I copy the example from the readme.   So, no checkout action.

I've googled and found a couple of references to this error but I'm not groking if my issue is the same.  Any help would be appreciated. 

```
Run docker/build-push-action@v2
  with:
    push: true
    tags: xixiapdx/test_chord:latest
    cache-from: type=local,src=/tmp/.buildx-cache
    cache-to: type=local,dest=/tmp/.buildx-cache
    context: .
    file: ./Dockerfile
    pull: false
    no-cache: false
    load: false
    github-token: ***
📣 Buildx version: 0.4.2
🏃 Starting build...
/usr/bin/docker buildx build --tag xixiapdx/test_chord:latest --iidfile /tmp/docker-build-push-V9MMpy/iidfile --cache-from type=local,src=/tmp/.buildx-cache --cache-to type=local,dest=/tmp/.buildx-cache --file ./Dockerfile --push .
time="2020-10-03T20:53:06Z" level=warning msg="invalid non-bool value for BUILDX_NO_DEFAULT_LOAD: "
time="2020-10-03T20:53:06Z" level=warning msg="local cache import at /tmp/.buildx-cache not found due to err: could not read /tmp/.buildx-cache/index.json: open /tmp/.buildx-cache/index.json: no such file or directory"
#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 2B 0.1s done
#1 DONE 0.1s

#2 [internal] load .dockerignore
#2 transferring context: 2B 0.1s done
#2 DONE 0.1s
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /tmp/buildkit-mount119260378/Dockerfile: no such file or directory
Error: The process '/usr/bin/docker' failed with exit code 1
```

**Comment by crazy-max** [comment]
@XiXiaPdx Yes I also noticed that thanks to your PR. I just [pushed a patch](https://github.com/docker/build-push-action/pull/155). Can you retest it?

**Comment by XiXiaPdx** [comment]
> pushed a patch

✅  Excellent, it works. Thank you!

**Comment by XiXiaPdx** [comment]
I'm running a weird issue. Although the build and pushes, it appears the final image that is being produced contains directories/files that are in my .dockerignore file.  I did a quick search but I'm not sure if the action is suppose to respect the ignore file or not?

**Pull request closed without merging**
