### PR TITLE
Add support to pass `--ssh` flag to the build

### LINKED ISSUE #39: Feature request: provide way to add --ssh argument to docker build command
There does not appear to be a way to turn on the newish --ssh forwarding capability of docker build with this action.   This is needed to access private github repos from inside the Dockerfile (etc).  If this is in some way available, it is not documented.

Some way to place the ssh key(s) (or inject them from a repo secret) and get them to work with RUN --mount=type=ssh would be great.  If this ability is already present, then documentation would be greate!

### PR DESCRIPTION
**Pull request by jesserockz**
Closes #39

### CODE REVIEW

**Comment by tonistiigi** [comment]
Not sure if something like ssh agent socket makes sense in GH actions context. Maybe this should just take direct ssh key value from secrets and create a temp file to expose via `--ssh`.

**Comment by jesserockz** [comment]
That seems like it might be overcomplicating it and moving the action `ssh` key away from what the actual `--ssh` flag does. 
I start up an ssh agent with a key from a secret and forward that through with this method. 
The user would also be able to write the key to a file and expose that file themselves using this, if they choose to do it that way.

**Comment by tonistiigi** [comment]
Sorry, I forgot this issue. I'm fine with this approach but looks like PR needs a rebase.

**Review by crazy-max — CHANGES_REQUESTED** [review]
@jesserockz Need rebase like @tonistiigi said and you also need to run a `pre-checkin`. See https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md#submitting-a-pull-request

**Comment by jesserockz** [comment]
Thanks guys. I will take a look at rebasing again on Monday as I merged master on Friday and it broke our deployments.

**Comment by jesserockz** [comment]
I have rebased locally, but just waiting on a PR merge in our repo before I can push to the branch so it shows up here.

**Review by crazy-max — APPROVED** [review]
LGTM

**Review by tonistiigi — APPROVED** [review]

**Comment by jesserockz** [comment]
Thanks for merging. Any chance of a new tag/release so I can update our workflows? @crazy-max @tonistiigi

**Comment by crazy-max** [comment]
@jesserockz A new release will be created tomorrow.

**Pull request merged**
