### PR TITLE
Fix complete workflow

### LINKED ISSUE #165: Nightly builds have missing labels
#### Steps to reproduce this issue

1. Setup a repo with a complete example
2. Wait for the nightly schedule to trigger (or use a custom time to trigger it)

#### Expected behaviour

Labels should be filled with the proper values

#### Actual behaviour

Nightly builds have missing labels (when using the complete example):

```
    "org.opencontainers.image.url": "",
    "org.opencontainers.image.licenses": "",
    "org.opencontainers.image.source": ""
```

### Configuration

* Repository URL (if public): https://github.com/drakkan/sftpgo
* Build URL (if public): https://github.com/drakkan/sftpgo/runs/1214158303?check_suite_focus=true
* Package URL: https://github.com/users/drakkan/packages/container/sftpgo/111582

https://github.com/drakkan/sftpgo/blob/87f78b07b3bfc88bb821525f478f2dc8742c6a26/.github/workflows/docker.yml

### Logs

[logs_254.zip](https://github.com/docker/build-push-action/files/5333908/logs_254.zip)

## Root cause

The issue is caused by the [schedule](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#schedule) event not having a payload at all. Maybe using the [github](https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#github-context) context instead would make sense in this case

### PR DESCRIPTION
**Pull request by crazy-max**
Closes #165 

Signed-off-by: CrazyMax <crazy-max@users.noreply.github.com>

### CODE REVIEW

**Comment by sagikazarmark** [comment]
@crazy-max further thinking about this: does it really make sense to push a nightly image? I mean, 99% of the time it'll be the same as the edge version. This PR makes the complete workflow more complicated with very little benefit IMHO.

**Comment by crazy-max** [comment]
@sagikazarmark

> Further thinking about this: does it really make sense to push a nightly image?

Could be if base image is updated (frequently). This is just an example to show use cases and should not be taken literally. You can/should adapt it to your needs.

**Comment by sagikazarmark** [comment]
> You can/should adapt it to your needs.

Obviously, but people (myself included) will probably take a look at it and think it's "The Best Practice".

Anyway, here is my version: https://gist.github.com/sagikazarmark/0119e1f3dde0d8e755fd0ee5a5ef4cdc

Thanks for your time!

**Comment by crazy-max** [comment]
@sagikazarmark 

> Obviously, but people (myself included) will probably take a look at it and think it's "The Best Practice".

That's a good example IMHO but feel free to open a PR if you think it can be improved.

> Anyway, here is my version: https://gist.github.com/sagikazarmark/0119e1f3dde0d8e755fd0ee5a5ef4cdc

Your workflow looks good. About [`sha-${{ github.sha }}`](https://gist.github.com/sagikazarmark/0119e1f3dde0d8e755fd0ee5a5ef4cdc#file-ci-yml-L35), you should only include the 7 digits (`sha-${GITHUB_SHA::8}`). This [line](https://gist.github.com/sagikazarmark/0119e1f3dde0d8e755fd0ee5a5ef4cdc#file-ci-yml-L68) is also [not required](https://github.com/docker/login-action#dockerhub).

**Comment by sagikazarmark** [comment]
> Your workflow looks good. About [`sha-${{ github.sha }}`](https://gist.github.com/sagikazarmark/0119e1f3dde0d8e755fd0ee5a5ef4cdc#file-ci-yml-L35), you should only include the 7 digits (`sha-${GITHUB_SHA::8}`). This [line](https://gist.github.com/sagikazarmark/0119e1f3dde0d8e755fd0ee5a5ef4cdc#file-ci-yml-L68) is also [not required](https://github.com/docker/login-action#dockerhub).

Thanks a lot @crazy-max ❤️ much appreciated!

**Pull request merged**
