### PR TITLE
Ensure --progress=plain to avoid logs cutting

### PR DESCRIPTION
**Pull request by morlay**
When run `docker buildx build --progress=plain` will got all logs (default: "auto").

`build-push-action` used in github workflow. i think this always could be set.

### CODE REVIEW

**Comment by crazy-max** [comment]
@morlay Progress plain mode is automatically used in GitHub Runners because no tty is allocated so I don't think this is necessary. Also please run a `pre-checkin` (see https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md#submitting-a-pull-request).

**Comment by morlay** [comment]
@crazy-max i checked the results.

auto still cut logs of Dockerfile commands like RUN

**Comment by morlay** [comment]
Sorry. 
It may buildx issues. when running in small screen.

**Comment by Niek** [comment]
I'm also seeing a lot of repeat log output because of `--progress=auto` I assume. Is there any way to force plain progress?

**Comment by tonistiigi** [comment]
`progress=auto` is not a separate mode. It is just a switch between `tty` and `plain` depending if build is performed from a terminal or not.

**Pull request closed without merging**
