### PR TITLE
Add example to upload image as an artifact

### PR DESCRIPTION
**Pull request by crazy-max**
> https://github.com/docker/build-push-action/actions/runs/305063606
image

Signed-off-by: CrazyMax <crazy-max@users.noreply.github.com>

### CODE REVIEW

**Comment by tonistiigi** [comment]
Isn't it more common to upload the build result rather than the oci tarball of an image?

**Comment by crazy-max** [comment]
@tonistiigi 

> Isn't it more common to upload the build result rather than the oci tarball of an image?

I use the OCI tarball output to be able to import the image to a local registry for testing purpose (could be used on PR event for example cause secrets cannot be shared to auth against a registry). Build result can only be exported through cache right?

**Comment by tonistiigi** [comment]
Why wouldn't you then just push to the local registry. Or is this for loading the image in another job? Looks unclear why anyone would want to do this. We should explain what problem the user is trying to solve by uploading an artifact and then do the complete example.

**Comment by crazy-max** [comment]
Seen together in Slack DM. Closing it as it could confuse some users.

**Pull request closed without merging**
